### ISSUE TITLE
unsupported system : freebsd

### ISSUE THREAD

**Issue by ex1maragda** [rhasspy/webrtc-noise-gain#6] opened 2023-10-05 10:55 UTC
when I try to install with "pip install webrtc-noise-gain" get the following error (Unsupported system: freebsd):
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/usr/local/share/homeassistant/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/share/homeassistant/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/share/homeassistant/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-sdqfvtln/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-sdqfvtln/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-sdqfvtln/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-sdqfvtln/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 384, in <module>
      ValueError: Unsupported system: freebsd
      [end of output]

**Comment by LukaszMoskala** [comment] 2023-10-05 12:35
same problem here. Looks like error is thrown here: https://github.com/rhasspy/webrtc-noise-gain/blob/0b3bc23f5f33101df5b8f1970919500d8629b955/setup.py#L384

I'll try to patch it to threat freebsd the same way as linux and see what will happen.

**Comment by LukaszMoskala** [comment] 2023-10-05 13:43
Just treating it as linux is not enough. So far pip doesn't complain, however both clang, gcc12 and gcc13 fail to build something that is required.

gcc13 complains about `/usr/local/include/python3.11/pymacro.h:10:25: error: '_Static_assert' was not declared in this scope; did you mean 'static_assert'?`

clang complains about
```
/tmp/pip-req-build-qixxzok2/webrtc-audio-processing/webrtc-audio-processing-1/rtc_base/platform_thread_types.cc:46:10: error: cast from pointer to smaller type 'rtc::PlatformThreadId' (aka 'int') loses information
        return reinterpret_cast<PlatformThreadId>(pthread_self());
```

I think the problem may be in webrtc-audio-processing library itself but hopefully someone who knows more than me will speak about that.

If someone wants to install it themselves, then I used `pip3 install  git+https://github.com/LukaszMoskala/webrtc-noise-gain.git` or `CC=gcc13 CXX=g++13 pip3 install  git+https://github.com/LukaszMoskala/webrtc-noise-gain.git`

**Comment by amigan** [comment] 2023-10-05 14:41
https://github.com/rhasspy/webrtc-noise-gain/pull/7

**Comment by LukaszMoskala** [comment] 2023-10-05 14:47
Just in time when I also fixed it (at least it builds, I don't know yet if it actually works).

I'll be trying whatever I did later tonight, but if someone wants to try my code, I just did `pip3 install git+https://github.com/LukaszMoskala/webrtc-noise-gain.git` and it worked. I don't know if homeassistant with this will actually start

**Comment by amigan** [comment] 2023-10-05 15:03
HA starts with my patch. I am actually using the voice stuff, so I will test later and see if everything is in order.

**Comment by amigan** [comment] 2023-10-05 21:47
It looks like voice assist isn't working, but I really don't think it is because of any of this. I see data going to whisper in a packet capture, but nothing happens after that.

**Comment by LukaszMoskala** [comment] 2023-10-06 18:29
Looks like removing `default_config:` from configuration and including whatever it used to include manually, but skipping `assist_pipeline` should work as a workaround untill your patch is merged.

Also your patch installs correctly, however my homeassistant still does not start, due to unrelated (I belive) problems with numpy so I'm not able to test it now

**Comment by ryanwinter** [comment] 2023-10-09 23:54
I believe the esphome plugin depends on the assist_pipeline so this will need to be disabled as well.

**Comment by gdt** [comment] 2023-10-14 12:30
I'm seeing the same unsupported error with netbsd.

**Comment by tuarrep** [comment] 2023-10-17 17:03
I can confirm that
1. the package is installing with the patch.
2. HA starts after manually installing that patch and without disabling any module.

I do not use voice stuff, so I cannot confirm it's effectively working on my side.

**Comment by synesthesiam** [comment] 2023-10-18 20:21
PR has been merged. Let me know if the issue has been resolved.

**Comment by gdt** [comment] 2023-10-18 23:26
I didn't notice this when I read the PR, but the meson patch adds dragonfly/freebsd/netbsd/openbsd (yay) but the setup.py only adds freebsd.  I have a patch to fix setup.py to have all 4; see #11.

**Comment by gdt** [comment] 2023-10-18 23:29
Also, does anyone understand what's going on with https://gitlab.freedesktop.org/pulseaudio/webrtc-audio-processing/ ?  Looking at pull requests for OS support being open for years, It does not immediately appear healthy.   It's really nice to see things getting merged here.

**Comment by gdt** [comment] 2023-10-19 12:09
I realize there is still an open question as to whether the BSD support is 100% working, but coming here as a hass user I see the "hass fails to install on BSD" as really serious and "new feature for voice commands doesn't work" as much less so, in terms of urgency to resolve and not being so much of a regression.

Therefore I think it would be good to tag a release and ask HA upstream to merge a bump, so that 2023.11 will install ok.  And yes, I realize that there is a likelihood of needing a new release and bump next month, but I think that' s ok; we won't run out of integers to label them with!

**Comment by amigan** [comment] 2023-10-19 13:56
The home assistant maintainers are actively hostile to anyone not using their own Linux distribution, so good luck with that.

**Comment by gdt** [comment] 2023-10-19 14:20
I know, but a release and bump is still fair with 'bug fixes' :-)

**Comment by crees** [comment] 2023-10-20 21:00
Thankfully this is the first result in Google for "webrtc-noise-gain freebsd" which I think is the obvious thing to search.  Thanks for the work done here :)

(I also don't care about the voice stuff :))

**Comment by amigan** [comment] 2023-10-21 15:03
I have just verified that this patch and all voice functionality are working on FreeBSD in 2023.10.4.

**Comment by synesthesiam** [comment] 2023-10-23 22:51
> The home assistant maintainers are actively hostile to anyone not using their own Linux distribution, so good luck with that.

I don't know about your specific experience, but I believe it's largely an issue of limited human resources.

**Closed as completed by synesthesiam** 2023-10-23 22:51 UTC

**Comment by amigan** [comment] 2023-10-23 22:59
> > The home assistant maintainers are actively hostile to anyone not using their own Linux distribution, so good luck with that.
> 
> I don't know about your specific experience, but I believe it's largely an issue of limited human resources.

Thank you for closing. I just wanted to say that they refuse any and all patches that would help. I'm not expecting white glove support; FreeBSD users are very much a self-supporting bunch.

**Comment by synesthesiam** [comment] 2023-10-24 01:37
Fair enough. I don't know anyone at Nabu Casa who uses FreeBSD as their daily driver. I have it indirectly via TrueNAS, but I'm also a little unusual within the team for running vanilla Debian 😄

**Comment by precurse** [comment] 2023-12-01 21:37
Running Home Assistant in a jail, as opposed to a full fledged BHyve Linux instance, is so much more appealing to me. The fact upgrading to a newer version broke the Home Assistant mobile app for me is highly annoying.

Edit: Ahh, looks like they never cut a release since the freebsd patch was implemented -- so pip tries to install version 1.2.3 without the patch and fails. `pip3 install git+https://github.com/rhasspy/webrtc-noise-gain.git` seems to have done the trick.

**Comment by pixel8383** [comment] 2024-07-31 07:17
Hello, I am stuck on this issue and (sorry) but can't find out what I am doing wrong:

When starting homeassistant in a jail (running on FreeBSD 13.3 with Python3.11) inside the homeassistant.log file I get:

```
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/usr/local/share/homeassistant/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/share/homeassistant/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/share/homeassistant/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-pm0608a2/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-pm0608a2/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-pm0608a2/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-pm0608a2/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 384, in <module>
      ValueError: Unsupported system: freebsd
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

As suggested I have tried to do the following:
1. Activate the venv with `source /usr/local/share/homeassistant/bin/activate`
2. Install webrtc-noise-gain patched version with `pip3 install git+https://github.com/rhasspy/webrtc-noise-gain.git` and it seems to be instialled fine:
```
Collecting git+https://github.com/rhasspy/webrtc-noise-gain.git
  Cloning https://github.com/rhasspy/webrtc-noise-gain.git to /tmp/pip-req-build-5so4bgwm
  Running command git clone --filter=blob:none --quiet https://github.com/rhasspy/webrtc-noise-gain.git /tmp/pip-req-build-5so4bgwm
  Resolved https://github.com/rhasspy/webrtc-noise-gain.git to commit 558acbbe6b4e63eac78ee7808c22fe6eb4753fb9
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
```
When I do start HomeAssistant, anyhow, I always get the same error log as above.

What am I missing? What can I do to fix it?

Thank you!

**Comment by LukaszMoskala** [comment] 2024-07-31 07:29
You likely installed newer version than homeassistant requires, so homeassistant tries to downgrade it on startup.

You probably need to install older version with something like `pip3 install git+https://github.com/rhasspy/webrtc-noise-gain.git#7be98ca4bd7f4218d5a63d40eff8e73882356da3` (be careful, your shell may treat commit number as comment).

I did not verify if this commit is correct and if it will work but that's probably what's happening, as, IIRC, homeassistant still uses version from before #7 was merged.


Also keep in mind that latest homeassistant versions require python 3.12 so that also may or may not be a problem.

**Comment by pixel8383** [comment] 2024-07-31 07:58
Hello @LukaszMoskala you are right, I checked with `pip list` and I discovered that the patch is v.1.2.5. This leads HomeAssistant to try to install the (broken) 1.2.3 version. 
I uninstalled it and I am trying with your suggestion now. I will let you know!

**Comment by pixel8383** [comment] 2024-07-31 08:12
Hello, @LukaszMoskala it seems like your suggested alternative version is still 1.2.5. This leads HomeAssistant to act the same. How can I install a patched 1.2.3 version? HomeAssistant needs webrtc-noise-gain==1.2.3 and any difference in version will lead HA to try a new install...

**Comment by badrpc** [comment] 2024-07-31 08:39
Hi @pixel8383,
I can recommend the following guide I found on the Internet: https://blog.brendans-bits.com/posts/2024/home-assistant-2024.7-jail/
It has the exact command to install required version plus a lot of other useful information.

**Comment by pixel8383** [comment] 2024-07-31 09:16
Hello @badrpc thanks for your input! I am not running FreeBSD 14 but I was able to use the suggested commit and it seems to be working now!

**Comment by gdt** [comment] 2024-07-31 11:37
You need something like `--skip-pip-packages aioesphomeapi` on the HA command line, to tell it not to insist on its version.
